In [1]:
import numpy as np

# Create a 1D array

arr1 = np.array([1,2,3]) # [0,1,2] or [-3,-2,-1]

print(arr1)

[1 2 3]


In [2]:
# check the array

print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
# Check the shape of the array

print(arr1.shape)

(3,)


In [4]:
# accessing elements from the array

arr1[2]

3

In [5]:
# Change an element from the array

arr1[2]= 5

In [6]:
arr1

array([1, 2, 5])

In [7]:
# Create a 2D array

arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
# Check the shape of the array

print("The shape is 2 rows and 3 columns:", arr2.shape)

The shape is 2 rows and 3 columns: (2, 3)


In [9]:
# Accessing elements from the array

arr2[0][2]

3

In [10]:
arr2[0,2]

3

In [11]:
arr2[0,-2]

2

In [12]:
arr2[0,-1]

3

In [13]:
arr2[-1, 0]

4

In [14]:
# Array of type string

arr3 = np.array(['Nguyễn', 'Quang', 'Quốc' , ''])
print(arr3)

['Nguyễn' 'Quang' 'Quốc' '']


In [15]:
arr3[0]

'Nguyễn'

In [16]:
# Array of evenly spaced values within a specified interval

arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [17]:
# Array of evenly spaced number in a specified interval

arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [18]:
# Array of random values between 0 and 1 in a given shape

arr = np.random.rand(10)
print(arr)
print('\n')
arr = np.random.rand(3,4)
print(arr)

[0.6075778  0.60802832 0.26273931 0.11703406 0.73550116 0.36710199
 0.40506395 0.16200976 0.34895495 0.61997046]


[[0.21559377 0.20315492 0.37677799 0.7542783 ]
 [0.75779045 0.38391252 0.81677467 0.45279459]
 [0.6899188  0.75438306 0.52499409 0.30289627]]


In [19]:
# Array of zeros

print(np.zeros(10))
print('\n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
# Array of constant values in a given shape

print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [22]:
# Create an array by repetition
# epeat each element of an array by a specified number of times

arr = [0, 1, 2]
print(np.repeat(arr, 3)) 

[0 0 0 1 1 1 2 2 2]


In [23]:
# Repeat an array by a specified number of times

arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [24]:
# Create an idenity matrix

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# Create a matrix with a specified diagonal array

arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [27]:
arr = np.random.rand(5,5)
print(arr)

[[0.36939982 0.51247229 0.96500001 0.30597415 0.10851258]
 [0.95632129 0.04417551 0.84592568 0.1520066  0.77888084]
 [0.58158985 0.68459433 0.13609565 0.8511712  0.69290103]
 [0.8496995  0.04039759 0.1952327  0.97580702 0.14361559]
 [0.39752498 0.96686542 0.90051562 0.95215937 0.40403817]]


In [28]:
# Extract the diagonal elements in the array
print(np.diag(arr))

[0.36939982 0.04417551 0.13609565 0.97580702 0.40403817]


In [29]:
# Display the length of the array
print(len(arr))

5


In [30]:
# Display the dimension of the array
print(arr.ndim)

2


In [31]:
# Display the size of the elements
print(arr.size)

25


In [32]:
# print 4 random integers

print(np.random.randint(-10, 10, 4))

[-10  -6  -8   8]


In [33]:
# Mathematical operations

print(arr + 10)
print('\n')
print(arr - 10)
print('\n')
print(arr * 10)
print('\n')
print(arr / 10)

[[10.36939982 10.51247229 10.96500001 10.30597415 10.10851258]
 [10.95632129 10.04417551 10.84592568 10.1520066  10.77888084]
 [10.58158985 10.68459433 10.13609565 10.8511712  10.69290103]
 [10.8496995  10.04039759 10.1952327  10.97580702 10.14361559]
 [10.39752498 10.96686542 10.90051562 10.95215937 10.40403817]]


[[-9.63060018 -9.48752771 -9.03499999 -9.69402585 -9.89148742]
 [-9.04367871 -9.95582449 -9.15407432 -9.8479934  -9.22111916]
 [-9.41841015 -9.31540567 -9.86390435 -9.1488288  -9.30709897]
 [-9.1503005  -9.95960241 -9.8047673  -9.02419298 -9.85638441]
 [-9.60247502 -9.03313458 -9.09948438 -9.04784063 -9.59596183]]


[[3.69399815 5.12472288 9.6500001  3.05974148 1.0851258 ]
 [9.56321289 0.44175514 8.45925677 1.52006595 7.78880842]
 [5.81589846 6.84594329 1.36095654 8.511712   6.92901031]
 [8.49699502 0.4039759  1.95232701 9.75807017 1.43615587]
 [3.97524979 9.66865419 9.00515616 9.52159372 4.04038171]]


[[0.03693998 0.05124723 0.0965     0.03059741 0.01085126]
 [0.09563213 

In [34]:
# Exponentiation

print(np.exp(arr))

[[1.44686597 1.66941337 2.62478768 1.3579472  1.11461893]
 [2.60210645 1.04516578 2.33013377 1.16416791 2.17903222]
 [1.78888022 1.98296724 1.14579149 2.34238865 1.99950776]
 [2.3389439  1.04122467 1.21559382 2.65330761 1.15444024]
 [1.48813697 2.62968855 2.46087165 2.5912992  1.49786112]]


In [35]:
# Natural logarithm

print(np.log(arr))

[[-0.99587571 -0.66850864 -0.03562717 -1.18425466 -2.22088917]
 [-0.04466135 -3.11958462 -0.16732378 -1.88383137 -0.24989721]
 [-0.54198981 -0.37892884 -1.9943973  -0.161142   -0.3668681 ]
 [-0.16287252 -3.20898515 -1.63356309 -0.02449044 -1.94061508]
 [-0.92249751 -0.03369597 -0.10478777 -0.04902285 -0.90624592]]


In [36]:
# Base 2 logarithm

print(np.log2(arr))

[[-1.43674495 -0.9644541  -0.05139914 -1.70851833 -3.20406579]
 [-0.0644327  -4.50060927 -0.24139718 -2.71779417 -0.36052546]
 [-0.78192601 -0.54667875 -2.87730709 -0.23247876 -0.52927879]
 [-0.23497538 -4.62958696 -2.35673337 -0.03533224 -2.79971576]
 [-1.33088258 -0.048613   -0.1511768  -0.07072502 -1.3074365 ]]


In [37]:
# Base 10 logarithm

print(np.log10(arr))

[[-0.43250333 -0.29032961 -0.01547268 -0.51431527 -0.96451991]
 [-0.01939618 -1.35481839 -0.07266779 -0.81813757 -0.10852898]
 [-0.23538318 -0.1645667  -0.86615574 -0.06998308 -0.15932879]
 [-0.07073464 -1.39364454 -0.70944744 -0.01063606 -0.84279842]
 [-0.40063558 -0.01463397 -0.04550875 -0.02129035 -0.3935776 ]]


In [38]:
# sin function

print(np.sin(arr))

[[0.3610558  0.49033343 0.82204892 0.30122222 0.10829975]
 [0.81707622 0.04416115 0.74858519 0.15142189 0.70248335]
 [0.54935309 0.6323588  0.13567592 0.75205286 0.63877191]
 [0.75108205 0.0403866  0.19399482 0.82815449 0.14312241]
 [0.38713751 0.82310969 0.78364732 0.81466968 0.39313456]]


In [39]:
print(np.sin(180))

-0.8011526357338304


In [40]:
print(np.sin(0))

0.0


In [41]:
# cos function

print(np.cos(arr))

[[0.93254421 0.87153493 0.56941687 0.95355397 0.99411828]
 [0.57652967 0.99902442 0.66303862 0.98846923 0.71170017]
 [0.83559032 0.77467564 0.99075327 0.65910279 0.76939616]
 [0.66020887 0.99918413 0.98100255 0.5604999  0.98970499]
 [0.92202199 0.56788242 0.62120599 0.57992527 0.91948095]]


In [42]:
print(arr)

[[0.36939982 0.51247229 0.96500001 0.30597415 0.10851258]
 [0.95632129 0.04417551 0.84592568 0.1520066  0.77888084]
 [0.58158985 0.68459433 0.13609565 0.8511712  0.69290103]
 [0.8496995  0.04039759 0.1952327  0.97580702 0.14361559]
 [0.39752498 0.96686542 0.90051562 0.95215937 0.40403817]]


In [43]:
# sum along the row
print(np.sum(arr, axis=0))

[3.15453543 2.24850514 3.04276966 3.23711833 2.12794821]


In [44]:
# sum along the column
print(np.sum(arr, axis=1))

[2.26135884 2.77730992 2.94635206 2.2047524  3.62110356]


In [45]:
# minimum item value along the row
print(np.min(arr))

0.04039759004124954


In [46]:
print(np.max(arr))

0.9758070173565323


In [47]:
# calculate the overall mean

print(np.mean(arr))

0.5524350709365271


In [48]:
# calculate the mean along the row

print(np.mean(arr, axis=0))

[0.63090709 0.44970103 0.60855393 0.64742367 0.42558964]


In [49]:
# calculate the median
print(np.median(arr))

0.5815898464482628


In [50]:
# calculate the standard deviation
print(np.std(arr))

0.3350335391985332


In [51]:
# calculate the variance
print(np.var(arr))

0.11224747238789506


In [52]:
print(arr)
print('\n')
print(arr[1:3, 2:5])

[[0.36939982 0.51247229 0.96500001 0.30597415 0.10851258]
 [0.95632129 0.04417551 0.84592568 0.1520066  0.77888084]
 [0.58158985 0.68459433 0.13609565 0.8511712  0.69290103]
 [0.8496995  0.04039759 0.1952327  0.97580702 0.14361559]
 [0.39752498 0.96686542 0.90051562 0.95215937 0.40403817]]


[[0.84592568 0.1520066  0.77888084]
 [0.13609565 0.8511712  0.69290103]]


In [53]:
# Sort an array
arr = np.random.rand(5,5)
print(arr)

[[0.52337453 0.60020934 0.09733735 0.30933314 0.24304355]
 [0.35399133 0.50536304 0.32834841 0.48640425 0.60158642]
 [0.51970482 0.1699288  0.1083325  0.82894957 0.35413119]
 [0.86157299 0.73488587 0.77208851 0.61228507 0.01434011]
 [0.73369164 0.4044715  0.30011023 0.58847782 0.44538287]]


In [54]:
# sort along the column

print(np.sort(arr, axis=1))

[[0.09733735 0.24304355 0.30933314 0.52337453 0.60020934]
 [0.32834841 0.35399133 0.48640425 0.50536304 0.60158642]
 [0.1083325  0.1699288  0.35413119 0.51970482 0.82894957]
 [0.01434011 0.61228507 0.73488587 0.77208851 0.86157299]
 [0.30011023 0.4044715  0.44538287 0.58847782 0.73369164]]


In [55]:
# Transpose an array
print(arr)
print('\n')
print(arr.T)

[[0.52337453 0.60020934 0.09733735 0.30933314 0.24304355]
 [0.35399133 0.50536304 0.32834841 0.48640425 0.60158642]
 [0.51970482 0.1699288  0.1083325  0.82894957 0.35413119]
 [0.86157299 0.73488587 0.77208851 0.61228507 0.01434011]
 [0.73369164 0.4044715  0.30011023 0.58847782 0.44538287]]


[[0.52337453 0.35399133 0.51970482 0.86157299 0.73369164]
 [0.60020934 0.50536304 0.1699288  0.73488587 0.4044715 ]
 [0.09733735 0.32834841 0.1083325  0.77208851 0.30011023]
 [0.30933314 0.48640425 0.82894957 0.61228507 0.58847782]
 [0.24304355 0.60158642 0.35413119 0.01434011 0.44538287]]


In [56]:
print(arr.transpose())

[[0.52337453 0.35399133 0.51970482 0.86157299 0.73369164]
 [0.60020934 0.50536304 0.1699288  0.73488587 0.4044715 ]
 [0.09733735 0.32834841 0.1083325  0.77208851 0.30011023]
 [0.30933314 0.48640425 0.82894957 0.61228507 0.58847782]
 [0.24304355 0.60158642 0.35413119 0.01434011 0.44538287]]


In [57]:
# Flatten the 2D array

print(arr)
print('\n')
print(arr.flatten())

[[0.52337453 0.60020934 0.09733735 0.30933314 0.24304355]
 [0.35399133 0.50536304 0.32834841 0.48640425 0.60158642]
 [0.51970482 0.1699288  0.1083325  0.82894957 0.35413119]
 [0.86157299 0.73488587 0.77208851 0.61228507 0.01434011]
 [0.73369164 0.4044715  0.30011023 0.58847782 0.44538287]]


[0.52337453 0.60020934 0.09733735 0.30933314 0.24304355 0.35399133
 0.50536304 0.32834841 0.48640425 0.60158642 0.51970482 0.1699288
 0.1083325  0.82894957 0.35413119 0.86157299 0.73488587 0.77208851
 0.61228507 0.01434011 0.73369164 0.4044715  0.30011023 0.58847782
 0.44538287]


In [58]:
# Append elements to an array

arr = np.array([4,5,6,7])

In [59]:
arr1 = np.append(arr, 8)
arr1

array([4, 5, 6, 7, 8])

In [60]:
arr2 = np.append(arr, [9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [61]:
# Insert elements to an array

arr3 = np.insert(arr, 0, [12,13,14])
print(arr3)

[12 13 14  4  5  6  7]


In [62]:
# Remove elements from an array

print(arr)
print('\n')
arr4 = np.delete(arr, 0)
print(arr4)

[4 5 6 7]


[5 6 7]


In [63]:
# Delete multiple elements

print(arr2)
print('\n')
arr5 = np.delete(arr2, [1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [64]:
# Copy elements from an array

arr1 = np.arange(10, 40, 3)
arr1

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [65]:
arr_copy = np.copy(arr1)
arr_copy

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [66]:
arr_copy = arr1.copy()
print(arr_copy)

[10 13 16 19 22 25 28 31 34 37]


In [67]:
# Combine and split an array

arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [68]:
# Combine the array items by row

cat = np.concatenate((arr1,arr2), axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [69]:
# Combine array items by column

cat = np. concatenate((arr1, arr2), axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [70]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [71]:
# Stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [72]:
# Set operations

# Find elements from an array
arr = np.array([1,2,3,4,5,6,3,6,1,2,4])
print(np.unique(arr))

[1 2 3 4 5 6]


In [73]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


In [74]:
# Intersection of 2 array elements

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [75]:
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [76]:
# Union of 2 array elements

print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [77]:
# Elements present in first array but not in the second array
print(np.setdiff1d(arr1, arr2))
print(np.setdiff1d(arr2, arr1))

[1 2]
[6 7]


In [78]:
# Elements present in either of the arrays but not both

print(np.setxor1d(arr1, arr2))

[1 2 6 7]
